[[setting-up-client-tools]]
## Setting up client tools

In this Lab we will take a quick look at how to install the OpenShift CLI tools from an informative perspective as
we will be using another approach so we will *not* need to install it.

### Installing OpenShift CLI tools in your local environment

NOTE: This is just an informative section and *we can skip* for the lab execution purpose and move to <<login-and-config>>.

The CLI is provided as compressed files that can be decompressed to any
directory. In order to make it simple for any user to access the OpenShift
CLI, it is recommended that it is made available in a directory mapped
to the environment variable called `PATH` from the OS. More information
can be found about installation process here:
{{GET_STARTED_CLI_URL}}

1.  *OSX and Linux:*
+
1.1. Copy the binary to the `/usr/local/bin` directory, or one of the
paths listed in the `PATH` environment variable.
2.  *Windows:*
+
2.1. Use `oc.exe` to open an OpenShift shell. If you getting error from
running oc, go to http://git-scm.com to download git bash for Windows (during
installation you need to specify in the selection to integrate with the
command prompt)

[#login-and-config]
### User and Credentials
Users are previously created and you can assign yourself a login by adding your name {{ETHERPAD_USERS_LIST}}[here].


### Basic configuration

The easiest way to initially setup the OpenShift CLI is to use the
`oc login` command. It'll interactively ask you a server URL, username
and password. The information is automatically saved in a CLI
configuration file that is then used for subsequent commands.

. Open the terminal link {{TERMINAL_URL}}
. When asked for credentials use the login you assigned previously and the password `{{DEFAULT_PASSWORD}}`.

To login to a remote server use:

----
$ oc login {{CONSOLE_ADDRESS}}
----
