[[code-promotion-across-environments]]
### Code Promotion across Environments


In this lab we will learn how an application image binary can be
promoted across the environments. As an example we will use development
and QA environments as promotion to pre-prod and production will be very
similar.

In this example we are using projects as means of separation of
environments (development, qa, production).

*Step 1: Create two projects*

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

Using the knowledge you gained from the past create two projects. Name
them *development-userxx* and *testing-userxx*.
----
$ oc new-project development-userxx

$ oc new-project testing-userxx

----

*Step 2: Provide ImagePuller Access to the QA Project from Development Project*

The following command will allow the QA project to be able to pull the
docker images from the Development project.

....
$ oc policy add-role-to-group system:image-puller system:serviceaccounts:testing-userxx -n development-userxx
....

*Step 3: Create an application in the development project*

Switch over to the *development-userxx* project and deploy an
application using `eap64-basic-s2i` template. You can use web console or
command line. The command line option is shown below.

----
$ oc project development-userxx  

----

*Bonus points:* Clone this application to your own GitLab account and
deploy it so that you can redeploy with changes later.

....
oc project development-userxx
oc new-app openshift/php~https://github.com/RedHatWorkshops/welcome-php
....

*Step 4: Tag the docker image*

Wait until the application gets built and deployed. Now if you check the
`imagestreams` you will find the docker image for this application.

Now find the `imagestream` name using the following command. "is" is the
short form for `imagestream`.

----
oc get is
NAME          DOCKER REPO                                                      TAGS      UPDATED
welcome-php   docker-registry.default.svc:5000/development-user1/welcome-php   latest    About a minute ago
----

Now describe this image stream to get the full image id:

----
$ oc describe is welcome-php

Name:			welcome-php
Namespace:		development-user1
Created:		2 minutes ago
Labels:			app=welcome-php
Annotations:		openshift.io/generated-by=OpenShiftNewApp
Docker Pull Spec:	docker-registry.default.svc:5000/development-user1/welcome-php
Image Lookup:		local=false
Unique Images:		1
Tags:			1

latest
  no spec tag

  * docker-registry.default.svc:5000/development-user1/welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c
      About a minute ago
----

In this case, the full image Id is
`docker-registry.default.svc:5000/development-user1/welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c`

Now let us assume that this docker image is good and is ready to promote
to QA. Let us tag this docker image using the `oc tag` command.

The format is:

----
$ oc tag <IMAGE ID> development-userxx/myapp:promote-qa
----

Check the following commands and replace the values as your needs:
Dont forget to update below with your username  

----
$ oc tag \
development-UserName/welcome-php:latest \
development-UserName/welcome-php:promote-qa

Tag welcome-php:promote-qa set to development-user1/welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c.

$ oc describe is welcome-php

Name:			welcome-php
Namespace:		development-user1
Created:		5 minutes ago
Labels:			app=welcome-php
Annotations:		openshift.io/generated-by=OpenShiftNewApp
Docker Pull Spec:	docker-registry.default.svc:5000/development-user1/welcome-php
Image Lookup:		local=false
Unique Images:		1
Tags:			2

latest
  no spec tag

  * docker-registry.default.svc:5000/development-user1/welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c
      5 minutes ago

promote-qa
  tagged from welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c

  * docker-registry.default.svc:5000/development-user1/welcome-php@sha256:d6d55481339b9a929222827f132604438398c2ee085a86d02011602c9a96678c
      27 seconds ago
----

*Step 5: Deploy the application to QA*

Now you can switch over to the QA project and deploy the docker image
that we tagged in development. Also expose service to create route for
this project.

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

----
oc project testing-userxx
oc new-app development-userxx/welcome-php:promote-qa
oc expose service welcome-php
----

Test this application in the QA project. Note that we deployed the
docker image from the development project without rebuilding the code.

*Bonus points*: 
Go do your development project and execute a new build through the web-ui. 
Now find the latest `imagestream` that is pointing at your newly built image  and tag
it as `promote-qa`. Watch out that the testing project gets redeployed when you
update the new tag.

Watch this
https://blog.openshift.com/promoting-applications-across-environments[video]
for complete understanding.

Congratulations!! you now know how to promote your application across
environments in OpenShift 3.
