[[code-promotion-across-environments]]
## Code Promotion across Environments


In this lab we will learn how an application image binary can be
promoted across the environments. As an example we will use development
and QA environments as promotion to pre-prod and production will be very
similar.

In this example we are using projects as means of separation of
environments (development, qa, production).

### Create two projects

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

Using the knowledge you gained from the past create two projects. Name
them *development-userxx* and *testing-userxx*.

### Provide ImagePuller Access to the QA Project from Development Project

The following command will allow the QA project to be able to pull the
docker images from the Development project.

----
$ oc policy add-role-to-group system:image-puller system:serviceaccounts:testing-userxx -n development-userxx
----

### Create an application in the development project

Switch over to the *development-userxx* project and deploy an
application using `eap64-basic-s2i` template. You can use web console or
command line. The command line option is shown below.

*Bonus points:* Clone this application to your own GitLab account and
deploy it so that you can redeploy with changes later.

----
oc project development-userxx

oc new-app --template=eap64-basic-s2i -p APPLICATION_NAME=myapp -p SOURCE_REPOSITORY_URL=https://github.com/RedHatWorkshops/kitchensink.git -p SOURCE_REPOSITORY_REF="" -p CONTEXT_DIR="" -l name=myapp
----

### Tag the docker image

Wait until the application gets built and deployed. Now if you check the
`imagestreams` you will find the docker image for this application.

Now find the `imagestream` name using the following command. "is" is the
short form for `imagestream`.

----
$ oc get is
NAME      DOCKER REPO                                                 TAGS      UPDATED
myapp     docker-registry.default.svc:5000/development-userxx/myapp   latest    About a minute ago
----

Now describe this image stream to get the full image id:

----
$ oc describe is myapp

Name:			myapp
Namespace:		development-userxx
Created:		2 minutes ago
Labels:			app=eap64-basic-s2i
			application=myapp
			name=myapp
			template=eap64-basic-s2i
			xpaas=1.4.14
Annotations:		openshift.io/generated-by=OpenShiftNewApp
Docker Pull Spec:	docker-registry.default.svc:5000/development-userxx/myapp
Image Lookup:		local=false
Unique Images:		1
Tags:			1

latest
  no spec tag

  * docker-registry.default.svc:5000/development-userxx/myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a
      About a minute ago
----

In this case, the full image Id is
`docker-registry.default.svc:5000/development-userxx/myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a`

Now let's assume that this docker image is good and is ready to promote
to QA. Let's tag this docker image using the `oc tag` command.

The format is:

----
$ oc tag <IMAGE ID> development-userxx/myapp:promote-qa
----

Check the following commands and replace the values as your needs:

----
$ oc tag development-userxx/myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a development-userxx/myapp:promote-qa

$ oc describe is myapp

Name:			myapp
Namespace:		development-userxx
Created:		5 minutes ago
Labels:			app=eap64-basic-s2i
			application=myapp
			name=myapp
			template=eap64-basic-s2i
			xpaas=1.4.14
Annotations:		openshift.io/generated-by=OpenShiftNewApp
Docker Pull Spec:	docker-registry.default.svc:5000/development-userxx/myapp
Image Lookup:		local=false
Unique Images:		1
Tags:			2

latest
  no spec tag

  * docker-registry.default.svc:5000/development-userxx/myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a
      4 minutes ago

promote-qa
  tagged from myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a

  * docker-registry.default.svc:5000/development-userxx/myapp@sha256:007787a710c9ba352544fb2b5eefd0178b6156bea7be37d4c08f41e4e534a51a
      21 seconds ago
----

### Deploy the application to QA

Now you can switch over to the QA project and deploy the docker image
that we tagged in development. Also expose service to create route for
this project.

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

----
oc project testing-userxx

oc new-app development-userxx/myapp:promote-qa

oc expose service myapp
----

Test this application in the QA project. Note that we deployed the
docker image from the development project without rebuilding the code.

Watch this
https://blog.openshift.com/promoting-applications-across-environments[video]
for complete understanding.

Congratulations!! you now know how to promote your application across
environments in OpenShift 3.
