[[create-an-app-using-docker-build]]
## Create an App using Docker build

In this exercise we will learn how to create an application from a
Dockerfile. OpenShift takes Dockerfile as an input and generates your
application docker image for you.

### Create a project or use an existing project

If you want to, you can create a new project based on what you have
learned in the previous lab. Since we already have a project we will use
it. Run the following command to make sure.

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

----
$ oc project mycliproject-userxx
----

### Create an application that uses a Dockerfile

This time we will use a project that has a Dockerfile in a source code
repository. We will use a simple project on GitHub
(https://github.com/RedHatWorkshops/dockerbuildapp). "rhel" folder from this github
project is built starting with rhel7 as the base image which is
described in Dockerfile. Look at the Dockerfile for this project. It
starts off with `registry.access.redhat.com/rhscl/httpd-24-rhel7` image. It copies the
source code which is a simple `index.html` file and exposes port `8080`.


NOTE: When OpenShift finds a Dockerfile in the source, it uses
this Dockerfile as the basis to create a docker image for your
application. This strategy is called *Docker Build* strategy on
OpenShift. We'll see more about it when we look at the build
configuration a couple of steps down the line. Once OpenShift builds the
application's docker image, it stores that in a local docker registry.
Later it uses this image to deploy an application that runs in a pod.

Now let's create an application using this approach. We will run
`oc new-app` command by supplying the git uri as the parameter.

----
$ oc new-app https://github.com/RedHatWorkshops/dockerbuildapp --context-dir=rhel

--> Found Docker image 510d1c5 (3 weeks old) from registry.access.redhat.com for "registry.access.redhat.com/rhscl/httpd-24-rhel7"

    Apache httpd 2.4
    ----------------
    Apache httpd 2.4 available as container, is a powerful, efficient, and extensible web server.
    Apache supports a variety of features, many implemented as compiled modules which extend the core functionality.
    These can range from server-side programming language support to authentication schemes.
    Virtual hosting allows one Apache installation to serve many different Web sites.

    Tags: builder, httpd, httpd24

    * An image stream tag will be created as "httpd-24-rhel7:latest" that will track the source image
    * A Docker build using source code from https://github.com/RedHatWorkshops/dockerbuildapp will be created
      * The resulting image will be pushed to image stream tag "dockerbuildapp:latest"
      * Every time "httpd-24-rhel7:latest" changes a new build will be triggered
    * This image will be deployed in deployment config "dockerbuildapp"
    * Ports 8080/tcp, 8443/tcp will be load balanced by service "dockerbuildapp"
      * Other containers can access this service through the hostname "dockerbuildapp"

--> Creating resources ...
    imagestream.image.openshift.io "httpd-24-rhel7" created
    imagestream.image.openshift.io "dockerbuildapp" created
    buildconfig.build.openshift.io "dockerbuildapp" created
    deploymentconfig.apps.openshift.io "dockerbuildapp" created
    service "dockerbuild" created
--> Success
    Build scheduled, use 'oc logs -f bc/dockerbuildapp' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/dockerbuildapp'
    Run 'oc status' to view your app.
----

You'll notice that OpenShift created a few things at this point. You
will find a `buildconfig`, `deploymentconfig`, `service` and `imagestreams` in
the above list. The application is not running yet. It needs to be built
and deployed. Within a minute or so, you will see that OpenShift starts
the build.

### Build

In the meanwhile lets have a look at the `buildconfig` by running the
command shown below.

----
$ oc get bc dockerbuild -o json

{
    "apiVersion": "build.openshift.io/v1",
    "kind": "BuildConfig",
    "metadata": {
        "annotations": {
            "openshift.io/generated-by": "OpenShiftNewApp"
        },
        "creationTimestamp": "2019-02-20T00:32:54Z",
        "labels": {
            "app": "dockerbuildapp"
        },
        "name": "dockerbuildapp",
        "namespace": "mycliproject-userxx",
        "resourceVersion": "292476",
        "selfLink": "/apis/build.openshift.io/v1/namespaces/mycliproject-userxx/buildconfigs/dockerbuildapp",
        "uid": "103f77ec-34a7-11e9-acdb-0a0eee487cae"
    },
    "spec": {
        "failedBuildsHistoryLimit": 5,
        "nodeSelector": null,
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "dockerbuildapp:latest"
            }
        },
        "postCommit": {},
        "resources": {},
        "runPolicy": "Serial",
        "source": {
            "contextDir": "rhel",
            "git": {
                "uri": "https://github.com/RedHatWorkshops/dockerbuildapp"
            },
            "type": "Git"
        },
        "strategy": {
            "dockerStrategy": {
                "from": {
                    "kind": "ImageStreamTag",
                    "name": "httpd-24-rhel7:latest"
                }
            },
            "type": "Docker"
        },
        "successfulBuildsHistoryLimit": 5,
        "triggers": [
            {
                "github": {
                    "secret": "ERuRy3B_Frgyu3SLxViH"
                },
                "type": "GitHub"
            },
            {
                "generic": {
                    "secret": "4HWeLrwSTz-XBY3ng3Zh"
                },
                "type": "Generic"
            },
            {
                "type": "ConfigChange"
            },
            {
                "imageChange": {
                    "lastTriggeredImageID": "registry.access.redhat.com/rhscl/httpd-24-rhel7@sha256:1520e04b65b8e55d4ce0766b978767f3c63c315a3fa7b2f6e30e6860a9a5e359"
                },
                "type": "ImageChange"
            }
        ]
    },
    "status": {
        "lastVersion": 1
    }
}
----

Note the name of the `buildconfig` in metadata is set to *dockerbuildapp*, the git
uri pointing to the value you gave while creating the application. Also
note the Strategy.type set to *Docker*. This indicates that the build
will use the instructions in this Dockerfile to do the docker build.

Build starts in a minute or so. You can view the list of builds using
`oc get builds` command. You can also start the build using
`oc start-build dockerbuildapp` where *dockerbuildapp* is the name we noticed in the
`buildconfig`.

----
$ oc get builds
NAME               TYPE      FROM      STATUS    STARTED         DURATION
dockerbuildapp-1   Docker    Git       Running   8 seconds ago
----

Note the name of the build that is running i.e. `dockerbuildapp-1`. We will use that
name to look at the build logs. Run the command as shown below to look
at the build logs. This will run for a few mins. At the end you will
notice that the docker image is successfully created and it will start
pushing this to OpenShift internal docker registry.

----
$ oc logs build/dockerbuildapp-1

Successfully built 3d1211ef5f1f

Pushing image docker-registry.default.svc:5000/mycliproject-userxx/dockerbuildapp:latest ...
Pushed 1/5 layers, 22% complete
Pushed 2/5 layers, 40% complete
Push successful
----

In the above log note how the image is pushed to the local docker registry.
The registry is available by the internal service name `docker-registry.default.svc` at port `5000`.

### Deployment

Once the image is pushed to the docker registry, OpenShift will trigger a deploy process.
Let us also quickly look at the deployment configuration by running the following command. Note `dc` represents
`deploymentconfig`.

----
$ oc get dc -o json

{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "apps.openshift.io/v1",
            "kind": "DeploymentConfig",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftNewApp"
                },
                "creationTimestamp": "2019-02-20T00:43:16Z",
                "generation": 2,
                "labels": {
                    "app": "dockerbuildapp"
                },
                "name": "dockerbuildapp",
                "namespace": "mycliproject-userxx",
                "resourceVersion": "294360",
                "selfLink": "/apis/apps.openshift.io/v1/namespaces/mycliproject-userxx/deploymentconfigs/dockerbuildapp",
                "uid": "82d6aaff-34a8-11e9-acdb-0a0eee487cae"
            },
            "spec": {
                "replicas": 1,
                "revisionHistoryLimit": 10,
                "selector": {
                    "app": "dockerbuildapp",
                    "deploymentconfig": "dockerbuildapp"
                },
                "strategy": {
                    "activeDeadlineSeconds": 21600,
                    "resources": {},
                    "rollingParams": {
                        "intervalSeconds": 1,
                        "maxSurge": "25%",
                        "maxUnavailable": "25%",
                        "timeoutSeconds": 600,
                        "updatePeriodSeconds": 1
                    },
                    "type": "Rolling"
                },
                "template": {
                    "metadata": {
                        "annotations": {
                            "openshift.io/generated-by": "OpenShiftNewApp"
                        },
                        "creationTimestamp": null,
                        "labels": {
                            "app": "dockerbuildapp",
                            "deploymentconfig": "dockerbuildapp"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "image": "docker-registry.default.svc:5000/mycliproject-userxx/dockerbuildapp@sha256:8b06f694894a69d58dda3bea6ffa3cf4f379c7e559020e4bd1a4dec5baa29bfa",
                                "imagePullPolicy": "Always",
                                "name": "dockerbuildapp",
                                "ports": [
                                    {
                                        "containerPort": 8080,
                                        "protocol": "TCP"
                                    },
                                    {
                                        "containerPort": 8443,
                                        "protocol": "TCP"
                                    }
                                ],
                                "resources": {},
                                "terminationMessagePath": "/dev/termination-log",
                                "terminationMessagePolicy": "File"
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Always",
                        "schedulerName": "default-scheduler",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30
                    }
                },
                "test": false,
                "triggers": [
                    {
                        "type": "ConfigChange"
                    },
                    {
                        "imageChangeParams": {
                            "automatic": true,
                            "containerNames": [
                                "dockerbuildapp"
                            ],
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "dockerbuildapp:latest",
                                "namespace": "testlabs"
                            },
                            "lastTriggeredImage": "docker-registry.default.svc:5000/mycliproject-userxx/dockerbuildapp@sha256:8b06f694894a69d58dda3bea6ffa3cf4f379c7e559020e4bd1a4dec5baa29bfa"
                        },
                        "type": "ImageChange"
                    }
                ]
            },
            "status": {
                "availableReplicas": 1,
                "conditions": [
                    {
                        "lastTransitionTime": "2019-02-20T00:43:35Z",
                        "lastUpdateTime": "2019-02-20T00:43:35Z",
                        "message": "Deployment config has minimum availability.",
                        "status": "True",
                        "type": "Available"
                    },
                    {
                        "lastTransitionTime": "2019-02-20T00:43:35Z",
                        "lastUpdateTime": "2019-02-20T00:43:35Z",
                        "message": "replication controller \"dockerbuildapp-1\" successfully rolled out",
                        "reason": "NewReplicationControllerAvailable",
                        "status": "True",
                        "type": "Progressing"
                    }
                ],
                "details": {
                    "causes": [
                        {
                            "type": "ConfigChange"
                        }
                    ],
                    "message": "config change"
                },
                "latestVersion": 1,
                "observedGeneration": 2,
                "readyReplicas": 1,
                "replicas": 1,
                "unavailableReplicas": 0,
                "updatedReplicas": 1
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
----

Note where the image is picked from. It shows that the deployment picks
the image from the local registry and the image tag is same as what we built earlier. This
means the deployment step deploys the application image what was built
earlier during the build step.

If you get the list of pods, you'll notice that the application gets
deployed quickly and starts running in its own pod.

----
$ oc get pods

NAME                     READY     STATUS      RESTARTS   AGE
dockerbuildapp-1-build   0/1       Completed   0          3m
dockerbuildapp-1-hkzx9   1/1       Running     0          3m
----

### Adding a route

This step is very much the same as what we did in the previous exercise.
We will check the service and add a route to expose that service.

----
$ oc get services

NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
dockerbuildapp   ClusterIP   172.30.253.94   <none>        8080/TCP,8443/TCP   4m
----

Here we expose the service as a route.

----
$ oc expose service dockerbuildapp
----

And then we check the route exposed.

----
$ oc get routes

NAME             HOST/PORT                                                         PATH      SERVICES         PORT       TERMINATION   WILDCARD
dockerbuildapp   dockerbuildapp-mycliproject-userxx.{{APPS_ADDRESS}}             dockerbuildapp   8080-tcp                 None
----

NOTE: Unlike in the previous lab, this time we did not use --hostname
parameter while exposing the service to create a route. OpenShift
automatically assigned the project name extension to the route name.

### Run the application

Now run the application by using the route you provided in the previous
step. You can use either curl or your browser.

----
$ curl dockerbuildapp-mycliproject-userxx.{{APPS_ADDRESS}}
Congratulations you just deployed your app by using a Docker build strategy!
----

Congratulations!! In this exercise you have learnt how to create, build
and deploy an application using OpenShift Docker Build strategy.
