[[binary-deployment-of-a-war-file]]
## Binary Deployment of a war file


In the past you have seen how OpenShift can take your existing java
code, build it and deploy the resultant docker image as an application.
OpenShift S2I process includes an assemble script that copies the source
code from a git repository, invokes a maven build, places the resultant
war file in the deployments folder, builds a new application image and
pushes that image into the registry.

But how about if you want OpenShift to deploy a war file that you built
yourself?

In this exercise you will learn to deploy a war file. We will assume
that you built your source code outside of OpenShift build process and
want to download the WAR file on your workstation.

### Create project & folder structure

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

----
$ oc new-project binarydeploy-userxx

$ mkdir binarytest && cd binarytest

$ mkdir deployments
----

### Create war file

Create a war file and place it in deployments directory.

As an example here we have a WAR file called `petstore.war` that we
renamed to `ROOT.war` and placed in the deployments folder (you can
download this example WAR file
https://raw.githubusercontent.com/VeerMuchandi/ps/master/deployments/ROOT.war[here]).

----
$ cd deployments
$ wget https://raw.githubusercontent.com/VeerMuchandi/ps/master/deployments/ROOT.war
$ cd ..
----

----
$ ls -lR

total 0
drwxr-xr-x  3 samuel  wheel  96 Feb 19 23:24 deployments

./deployments:
total 12024
-rw-r--r--@ 1 samuel  wheel  6155452 Feb 19 23:24 ROOT.war
----

### Using builder image

Create a new build using the builder image of your choice. Here we are
using JBoss EWS (tomcat 8) image. The flag `binary=true` indicates that
this build will use the binary content instead of the url to the source
code.

Now we will name the application as *myapp*. So all the artifacts will
get the name *myapp*.

----
$ oc new-build --image-stream=jboss-webserver31-tomcat8-openshift:1.2 --binary=true --name=myapp

--> Found image 48ba94f (4 months old) in image stream "openshift/jboss-webserver31-tomcat8-openshift" under tag "1.2" for "jboss-webserver31-tomcat8-openshift:1.2"

    JBoss Web Server 3.1
    --------------------
    Platform for building and running web applications on JBoss Web Server 3.1 - Tomcat v8

    Tags: builder, java, tomcat8

    * A source build using binary input will be created
      * The resulting image will be pushed to image stream tag "myapp:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label build=myapp ...
    imagestream.image.openshift.io "myapp" created
    buildconfig.build.openshift.io "myapp" created
--> Success
----

### Executing the build

Start the build by uploading the contents of your `deployments`
directory. Make sure you are in the parent folder where you created the
`deployments` folder inside previously. Remember the war file is in the
`deployments` folder. The jboss-ews builder image knows to copy the
contents of the `deployments` folder to the `deployments` directory and
then builds the application image.

----
$ oc start-build myapp --from-dir=.

Uploading directory "." as binary input for the build ...
.
Uploading finished
build.build.openshift.io/myapp-1 started
----

You can check the build logs by executing:

----
$ oc logs myapp-1-build

Using docker-registry.default.svc:5000/openshift/jboss-webserver31-tomcat8-openshift@sha256:4485c46c9a044f819827e9049b33ee8cec28329c00b2a9e022c451f2f01d14ad as the s2i builder image
Copying all war artifacts from /tmp/src directory into /opt/webserver/webapps for later deployment...
Copying all war artifacts from /tmp/src/deployments directory into /opt/webserver/webapps for later deployment...
'/tmp/src/deployments/ROOT.war' -> '/opt/webserver/webapps/ROOT.war'

Pushing image docker-registry.default.svc:5000/binarydeploy-userxx/myapp:latest ...
Pushed 0/7 layers, 2% complete
Pushed 1/7 layers, 14% complete
Push successful
----

### Create the application

Now create the application with the same name as what you gave for the
build.

Here we are using the name *myapp*, so that the rest of the objects such
as deployment configuration and service are created with the same name
and refer to the `imagestream` created earlier.

----
$ oc new-app myapp --allow-missing-imagestream-tags

--> Found image 4df05f5 (2 minutes old) in image stream "binarydeploy-userxx/myapp" under tag "latest" for "myapp"

    temp.builder.openshift.io/binarydeploy-userxx/myapp-1:54e93d8d
    --------------------------------------------------------------
    Platform for building and running web applications on JBoss Web Server 3.1 - Tomcat v8

    Tags: builder, java, tomcat8

    * This image will be deployed in deployment config "myapp"
    * Ports 8080/tcp, 8443/tcp, 8778/tcp will be load balanced by service "myapp"
      * Other containers can access this service through the hostname "myapp"

--> Creating resources ...
    deploymentconfig.apps.openshift.io "myapp" created
    service "myapp" created
--> Success
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/myapp'
    Run 'oc status' to view your app.
----

Now, expose the service as a route to be able to use it from the
browser.

----
$ oc expose svc myapp

route "myapp" exposed
----

You can use the route to access the application using the URL.
