[[using-ssl-in-your-application]]
## Using SSL in your application


In this exercise you will set up your application to encrypt traffic
with the OpenShift Wildcard certificate.

### Switch to an existing project

For this exercise, we will use an application that we created before. We
will be using the *myjbossapp-userxx* that you created in the previous
labs. Make sure you are switched to that project by using the `oc
project` command.

IMPORTANT: Please replace *userxx* with the username assigned to you in
the commands below.

----
$ oc project myjbossapp-userxx
----

### View the routing config

To view the routing config you will need to use the `oc get route`
command:

----
$ oc get route/ks -o yaml
----

You should get a result like this:

[source,yaml]
----
  apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/host.generated: "true"
    creationTimestamp: 2019-02-20T02:01:16Z
    labels:
      application: ks
      template: eap64-basic-s2i
      template.openshift.io/template-instance-owner: 680372a6-34b3-11e9-acdb-0a0eee487cae
      xpaas: 1.4.14
    name: ks
    namespace: myjbossapp-userxx
    resourceVersion: "307462"
    selfLink: /apis/route.openshift.io/v1/namespaces/myjbossapp-userxx/routes/ks
    uid: 68077bba-34b3-11e9-acdb-0a0eee487cae
  spec:
    host: ks-myjbossapp-userxx.{{APPS_ADDRESS}}
    to:
      kind: Service
      name: ks
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2019-02-20T02:01:16Z
        status: "True"
        type: Admitted
      host: ks-myjbossapp-userxx.{{APPS_ADDRESS}}
      routerName: router
      wildcardPolicy: None
----

Note here that the `host:` is set to the FQDN that your application is
running on.

Currently the routing component of OpenShift 3 supports ports `80` and
`443`. When you first create your route, the mapping of `80` to your pod
is done automatically. There are a few things that need to be done in
order to get the `443` mapping to work.

### TLS Edge Termination

OpenShift has a _wildcard_ SSL certificate that it can use for any
application. We can use this SSL certificate to serve SSL from our
application without having to generate a cert of our own (which is
sometimes called SSL-offloading).

Edit your routing configuration:

----
$ oc edit route/ks
----

You are going to add `tls: termination: edge` right below the `host:`
section. It should look something like this.

[source,yaml]
----
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2015-12-22T03:56:30Z
  labels:
    app: ks
  name: ks
  namespace: myjbossapp-shchan
  resourceVersion: "2903142"
  selfLink: /oapi/v1/namespaces/myjbossapp-userxx/routes/ks
  uid: fba5d1e6-a85f-11e5-be21-fa163ec58dad
spec:
  host: ks-myjbossapp-userxx.{{APPS_ADDRESS}}
  tls:
    termination: edge
  port:
    targetPort: "8080"
  to:
    kind: Service
    name: ks
status: {}
----

### Verify

Verify by visiting your page by using the `https://` URI

Congratulations!! In this exercise you have learned about service SSL
from your application
