OpenShift Workshop
===================
:email: <samuel@redhat.com>
:description: OpenShift presentation deck for workshop.
:revnumber: 0.1
///////////////////////
	Themes that you can choose includes:
	web-2.0, swiss, neon, beamer
///////////////////////
:deckjs_theme: swiss
///////////////////////
	Transitions that you can choose includes:
	fade, horizontal-slide, vertical-slide
///////////////////////
:deckjs_transition: fade
///////////////////////
	AsciiDoc use `source-highlight` as default highlighter.

	Styles available for pygment highlighter:
	monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
	tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

	Uncomment following two lines if you want to highlight your code
	with `Pygments`.
///////////////////////
:pygments:
:pygments_style: autumn
///////////////////////
	Uncomment following line if you want to scroll inside slides
	with {down,up} arrow keys.
///////////////////////
//:scrollable:
///////////////////////
	Uncomment following line if you want to link css and js file
	from outside instead of embedding them into the output file.
///////////////////////
//:linkcss:
///////////////////////
	Uncomment following line if you want to count each incremental
	bullet as a new slide
///////////////////////
//:count_nested:

== Setting up client tools

Let's login on our cluster:

--------
oc login <server url>
--------

== Create an App from a Docker image

Create a new project:
-------
oc new-project mycliproject-userxx --description="My CLI Project" --display-name="CLI Project"
-------

List all projects:
----
oc get projects
----
